/**
 * Report Template
 * Professional report PDF generation with metrics and sections
 */

const PRIMARY_COLOR = '#7c5cfc';
const SECONDARY_COLOR = '#34d399';

module.exports = function generateReport(data, doc) {
  const { title, subtitle, metrics, sections } = data;
  
  // Header
  doc.rect(0, 0, doc.page.width, 100).fill(PRIMARY_COLOR);
  doc.fill('#ffffff')
    .font('Helvetica-Bold')
    .fontSize(28)
    .text(title, 50, 30);
  
  if (subtitle) {
    doc.font('Helvetica')
      .fontSize(14)
      .text(subtitle, 50, 60);
  }
  
  // Reset
  doc.fill('#000000');
  
  // Metrics section
  if (metrics && metrics.length > 0) {
    doc.font('Helvetica-Bold')
      .fontSize(16)
      .fill(PRIMARY_COLOR)
      .text('Key Metrics', 50, 130);
    
    const metricBoxWidth = 150;
    const metricBoxHeight = 80;
    const metricStartX = 50;
    const metricY = 160;
    const metricGap = 20;
    
    metrics.forEach((metric, index) => {
      const x = metricStartX + index * (metricBoxWidth + metricGap);
      
      // Background
      doc.rect(x, metricY, metricBoxWidth, metricBoxHeight)
        .fill('#f8f9fa')
        .stroke();
      
      // Label
      doc.font('Helvetica')
        .fontSize(10)
        .fill('#666666')
        .text(metric.label, x + 10, metricY + 15);
      
      // Value
      doc.font('Helvetica-Bold')
        .fontSize(18)
        .fill(PRIMARY_COLOR)
        .text(metric.value, x + 10, metricY + 35);
    });
  }
  
  // Sections
  let currentY = metrics && metrics.length > 0 ? 270 : 150;
  
  if (sections && sections.length > 0) {
    sections.forEach((section) => {
      // Check for page break
      if (currentY > 700) {
        doc.addPage();
        currentY = 50;
      }
      
      // Section heading
      doc.font('Helvetica-Bold')
        .fontSize(14)
        .fill(PRIMARY_COLOR)
        .text(section.heading, 50, currentY);
      
      // Underline
      doc.moveTo(50, currentY + 18)
        .lineTo(200, currentY + 18)
        .lineWidth(2)
        .stroke(PRIMARY_COLOR);
      
      currentY += 30;
      
      // Section content
      doc.font('Helvetica')
        .fontSize(11)
        .fill('#333333')
        .text(section.content, 50, currentY, {
          width: 500,
          lineGap: 4
        });
      
      currentY += doc.heightOfString(section.content, {
        width: 500,
        lineGap: 4
      }) + 30;
    });
  }
  
  // Footer
  const footerY = doc.page.height - 40;
  doc.moveTo(50, footerY)
    .lineTo(doc.page.width - 50, footerY)
    .lineWidth(1)
    .stroke('#e5e7eb');
  
  doc.font('Helvetica')
    .fontSize(9)
    .fill('#9ca3af')
    .text(`Generated by DocForge | ${new Date().toLocaleDateString()}`, 50, footerY + 10);
  
  return doc;
};
